version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.5-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./conf.d/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    name: "${NETWORK_NAME:-nginx-proxy}"
